name: Deploy to server

on:
  push:
    branches:
      - Backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to server
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} <<'ENDSSH'
          cd ~/team-project-24spring-34/server/
          git pull
          pnpm install
          pkill -f "node src/server.js" || true
          nohup node src/server.js > nohup.out 2> nohup.err < /dev/null &
        ENDSSH