name: Deploy to server

on:
  push:
    branches:
      - Backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          /bin/bash
          source ~/.bashrc
          cd ~/team-project-24spring-34/server/
          git pull
          /home/ubuntu/.local/share/pnpm/pnpm install
          nohup /home/ubuntu/.local/share/pnpm/pnpm run start > /dev/null 2>&1 &
          exit
