name: Publish Docker image

on:
  push:
    branches: [main]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image for server
        uses: docker/build-push-action@v5
        with:
          context: ./server
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cs304-server:0.0.1, ${{ secrets.DOCKER_HUB_USERNAME }}/cs304-server:latest
      
      - name: Build and push Docker image for client
        uses: docker/build-push-action@v5
        with:
          context: ./client
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cs304-client:0.0.1, ${{ secrets.DOCKER_HUB_USERNAME }}/cs304-client:latest
        

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo docker stop cs304-server || true
            sudo docker rm cs304-server || true
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/cs304-server:0.0.1
            sudo docker run -d --name cs304-server -v  /home/ubuntu/server/.env:/usr/src/app/.env -p 80:8080 ${{ secrets.DOCKER_HUB_USERNAME }}/cs304-server:0.0.1
  