name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install Dependencies
      run: cd client && pnpm install

    - name: Run Tests
      run: cd client && pnpm test

    - name: Build
      run: cd client && pnpm run build